name: Test

on:
  push:
    branches: [ master, uwsgi-2.0 ]
  pull_request:
    branches: [ master, uwsgi-2.0 ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Add deadnakes ppa
      run: |
        sudo apt install -qqyf software-properties-common
        sudo add-apt-repository ppa:deadsnakes/ppa -y
    - name: Install dependencies
      run: |
        sudo apt update -qq
        sudo apt install --no-install-recommends -qqyf python{2.7,3.5,3.6,3.7,3.8}-dev \
          python3.8-distutils \
          libxml2-dev libpcre3-dev libcap2-dev \
          php7.2-dev libphp7.2-embed libargon2-0-dev libsodium-dev \
          liblua5.1-0-dev ruby2.5-dev \
          libjansson-dev libldap2-dev libpq-dev \
          libpam0g-dev libsqlite3-dev libyaml-dev \
          libzmq3-dev libmatheval-dev libperl-dev \
          libonig-dev libdb-dev libqdbm-dev libbz2-dev \
          libwrap0-dev libgeoip-dev libv8-dev libxslt1-dev \
          libboost-thread-dev libboost-filesystem-dev \
          libssl-dev libacl1-dev python-greenlet-dev \
          libcurl4-openssl-dev \
          openjdk-8-jdk libgloox-dev gccgo \
          cli-common-dev mono-devel mono-mcs uuid-dev \
          curl check
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: make tests
    - name: Build kitchensink uWSGI binary
      run: UWSGICONFIG_PHPPATH=php-config7.2 /usr/bin/python uwsgiconfig.py --build travis
    - name: Build uWSGI binary
      run: make
    - name: Build python2.7 plugin
      run: |
        /usr/bin/python2.7 -V
        /usr/bin/python2.7 uwsgiconfig.py --plugin plugins/python base python27
    - name: Build python3.5 plugin
      run: |
        /usr/bin/python3.5 -V
        /usr/bin/python3.5 uwsgiconfig.py --plugin plugins/python base python35
    - name: Build python3.6 plugin
      run: |
        /usr/bin/python3.6 -V
        /usr/bin/python3.6 uwsgiconfig.py --plugin plugins/python base python36
    - name: Build python3.7 plugin
      run: |
        /usr/bin/python3.7 -V
        /usr/bin/python3.7 uwsgiconfig.py --plugin plugins/python base python37
    - name: Build python3.8 plugin
      run: |
        /usr/bin/python3.8 -V
        /usr/bin/python3.8 uwsgiconfig.py --plugin plugins/python base python38
    - name: Build rack plugin
      run: |
        ruby -v
        UWSGICONFIG_RUBYPATH=ruby /usr/bin/python uwsgiconfig.py --plugin plugins/rack base rack251
    - name: Build cgi plugin
      run: |
        /usr/bin/python uwsgiconfig.py --plugin plugins/cgi base
    - name: Build dummy plugin
      run: |
        /usr/bin/python uwsgiconfig.py --plugin plugins/dummy base
    - name: Run smoke tests
      run: |
        ./tests/travis.sh .github/workflows/test.yml
